### ISSUE TITLE
keine fehlermeldung wenn js oder cookies deaktiviert sind

### ISSUE THREAD

**Issue by k3b** [strenkel/jshero#1]
Hallo stefan,

ich finde das ist eine gute idee, einen js-kurs via unittests zu implementieren.

mir ist folgendes aufgefallen:

* keine fehlermeldung, wenn js deaktiviert ist
* weiterblättern zur nächsten aufgabe funktioniert nur, wenn cookies freigeschaltet sind.

wenn ich für http://www.jshero.net/ im firefox-51.0.1 

* via noscript-5.03 js erlaube und 
* cookies aktzeptiere

funktioniert das tutorial wie gewünscht.

**Comment by strenkel** [comment]
Vielen Dank für den Hinweis! Ja, eine solche Fehlermeldung fehlt (obwohl ich nur localstorage und keine cookies verwende). Werde ich nachbessern.

**Comment by k3b** [comment]
keine cookies verwendet?

ich hatte zuerst nur js an und nach erfolgreicher aufgabe funktionierte der ">" aus "< # >" nicht. erst nachdem ich cookies angeschaltet hatte ging es. 

vielleicht habe ich einen bedienfehler gemacht

**Comment by strenkel** [comment]
Ich benutze wie gesagt nur localstorage und keine cookies. Wenn localstorage nicht funktioniert, geht die Navigation nicht. Ich vermute, dass das deaktivieren von Cookies auch Auswirkungen auf den localstorage hat. Aber das muss ich noch re­cher­chie­ren/testen.

**Comment by strenkel** [comment]
Ist jetzt gefixt:
(i) Es gibt eine Hinweismeldung, wenn kein  JavaScript aktiv ist (per noscript-Tag auf jeder Seite). Ohne JavaScript funktioniert JS Hero (in seiner jetzigen Fassung) überhaupt nicht.
(ii) Wenn localStorage nicht verfügbar ist, funktioniert alles außer das Speichern der Lösungen.
(iii) Es gibt einen entsprechende Hinweis auf den betroffenen Seiten, wenn localStorage nicht verfügbar ist.
