### ISSUE TITLE
Text in Lektion 3, Funktionen, verbessern!

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#12]
Bei diesem Koan http://www.jshero.net/main.html?koan=function stolperte ein Teilnehmer darüber, dass der Begriff Parameter nicht erklärt wird. Vielleicht sollte man das der Einfachheit halber an dieser Stelle erstmal weglassen.

**Comment by strenkel** [comment]
Wäre zu überlegen. Wäre näher dran an dem Prinziep "immer eine Sache nach der anderen einführen".
Alternative: Ein Verweis, dass Parameter später eingeführt werden.

**Comment by feinstaub** [comment]
Da die Parameter bereits im 6. Koan eingeführt werden, könnte man sie an dieser Stelle einfach weglassen. Für Lernende ist das Prinzip der kleinen Schritte immer gut. Zuviele Informationen führen zur Verwirrung.

**Comment by strenkel** [comment]
Hat sich erledigt.
