### ISSUE TITLE
14. String: indexOf(): Test zu leicht bestanden

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#13]
Der Test prüft derzeit nur auf "Feuer". Ein Teilnehmer hat das "Feuer" dann einfach in die Funktion hart-codiert (vergessen den Parameter zu verwenden) und damit den Test bestanden. Ein weiterer Test auf etwas anderes als "Feuer" würde dieses Problem lösen.

**Comment by strenkel** [comment]
Oh ja! Ad hoc würde ich sagen, den 2ten Test abändern. Das sollte reichen. Sollte unbedingt gemacht werden!

**Comment by Towabohu** [comment]
Ich habe einen Test auf Script in JavaScript eingebaut.

**Comment by feinstaub** [comment]
@Towabohu: wo ist der Test zu finden?

**Comment by Towabohu** [comment]
Moin, moin @feinstaub,

auf der aktuellen [Seiten](http://www.jshero.net/main.html?koan=stringindexof) im Repository.
Wenn Du folgenden Code einfügst siehst Du ihn.
<pre>
var indexOfIgnoreCase = function( text, toFind ) {
   var textUC = text.toUpperCase();
   var toFindUC = toFind.toUpperCase();
   return textUC.indexOf("FEUER");
};
</pre>

Ich hoffe, das ist so okay.

Grüße und frohes Fest

Mischa

**Comment by feinstaub** [comment]
Danke @Towabohu. Das funktioniert gut.

Ich hatte mir die Commits angeschaut und auf Anhieb nichts gefunden. Danach ich gesucht: https://github.com/strenkel/jshero/commit/614fa86822124abb9642ad64643240d94ca68128 "asserts eingebaut": ich dachte bei dem Commit ging es nur darum, den vorhandenen ausführlichen Code durch die Asserts zu ersetzen. Vielleicht beim nächsten Mal in der Commit-Message die Issue-Nummer erwähnen.

Ebenfalls schöne Feiertage.
