### ISSUE TITLE
9. Loggen: Die Hürde :-)

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#15]
Fürs Backlog: An diesem Koan http://www.jshero.net/main.html?koan=log bleiben die Teilnehmer regelmäßig hängen.

Ein Teilnehmer hatte auch nicht den Sinn verstanden, warum jshero.log zweimal aufgerufen werden sollte. Er sagte mir, dass er erst probiert hat, sich anhand der Test-Ausgabe zu erklären wie es gemeint war, aber er bekam es dennoch nicht hin.

Meine Gedanken dazu:
- Im kompletten restlichen JS-Hero (außer dem Playground) wird jshero.log nicht mehr benötigt.
- Besser fände ich, wenn die (oder eine weitere) Aufgabe so gestellt wäre, dass man mit console.log loggen soll und das dann in der Browser-Konsole selber überprüfen soll. Der Nachteil wäre zwar, dass keine automatische Testabdeckung möglich wäre. Der Vorteil wäre, dass man sich den Absatz mit den Erklärungen, warum bei der Übung jshero.log verwendet werden soll, sparen kann.

**Comment by strenkel** [comment]
Danke für den Hinweis! Vielleicht als Stichpunkte eine paar Anmerkungen:

* jshero.log wird zwar im kompletten JS-Hero nicht benötigt, ich dachte aber, dass man mithilfe dieses Loggens mache Aufgaben besser lösen kann. Wenn Schüler/innen nicht weiter kamen, konnte ich ihnen manchmal dadurch helfen, dass sie den Wert einer Variablen geloggt haben. Ich denke, dass loggen grundsätzlich wichtig ist, um Programmfehler zu finden.

* Ich habe jshero.log wegen mobile (Smartphone-Browser und Android-App) eingeführt. Da gibt es ja keine console.

* Der Text zur Übung #9 Loggen ist viel zu lang geworden. Und wahrscheinlich zu kompliziert.

* Ich könnte mir vorstellen, dass man console.log wrappen kann und so die Benutzung auch testen kann. Das nur so nebenbei.

Was also tun?

Ich würde (wegen mobile) an jshero.log festhalten. Ich würde dazu tendieren, jshero.log direkt (ohne console.log) einzuführen. Die Aufgabe müsste dann tatsächlich einfacher gestaltet sein und nur eine Logausgabe verlangen. Ggf. kann dann in einer zweiten Log-Übung das zweifache Loggen geübt werden. Und zum Schluss kann man ggf. kurz auf console.log eingehen und das als Alternative vorschlagen.

Eine Rückfrage:

Sollte man die jshero-Log-Ausgabe im Testergebnis besser darstellen? Aktuell sieht man es ja nur schwarz über dem Testergebnis. Vielleicht sollte man da noch irgendwie "Log" oder "Logausgabe" drüber/davor schreiben.

**Comment by feinstaub** [comment]
> Ich habe jshero.log wegen mobile (Smartphone-Browser und Android-App) eingeführt. Da gibt es ja keine console.

Ah, ok. Im Desktop-Umfeld ist es eher verwirrend. Letzte Stunde hat ein Schüler versucht, die Übung mit "console.log" zu lösen und hat sich gewundert, warum das nicht ging. Meine Erklärung war, dass console.log prinzipiell richtig ist, aber halt bei dieser einen Übung nicht...

> Ich könnte mir vorstellen, dass man console.log wrappen kann und so die Benutzung auch testen kann. Das nur so nebenbei.

Das wäre vielleicht was. Davon würde auch die Mobile-Version profitieren, weil man dann komplett auf jshero.log verzichten könnte.

> Ich würde dazu tendieren, jshero.log direkt (ohne console.log) einzuführen.

Wenn man an jshero.log festhalten will, wäre das vermutlich die bessere Variante. Meiner Ansicht sollte console.log aber nicht zu kurz kommen, weil gerade das den Zugang zur Browser-Konsole und den anderen Developer-Tools öffnet und es da viel zu entdecken gibt.

> Ggf. kann dann in einer zweiten Log-Übung das zweifache Loggen geübt werden

Mehr Übungen sind in dem Bereich sicher besser. Ich könnte mir auch etwas vorstellen, dass man nicht sagt, "hier, logge bitte genau an der Stelle", sondern eher so:
* "Hier schau, dieser Codeblock hat ein Problem, nutze Logging um herauszufinden, wo das Problem ist". Damit ließe sich der Sinn des Loggings besser begreifen. Oder
* "Lass diesen Codeblock laufen und finde mit Logging heraus, was die Ausgabe ist". Das wäre dann quizartig. Man könnte das auch in der aktuellen Implementierung umsetzen, indem man schreibt: "Schreibe eine Funktion, die das Ergebnis deiner Logging-Nachforschungen zurückgibt." :-)

> Eine Rückfrage:
> Sollte man die jshero-Log-Ausgabe im Testergebnis besser darstellen? Aktuell sieht man es ja nur schwarz über dem Testergebnis. Vielleicht sollte man da noch irgendwie "Log" oder "Logausgabe" drüber/davor schreiben.

Das ist auf jeden Fall hilfreich für die Schüler, die sich anhand der Testausgaben zur richtigen Lösung durchhangeln. Da hatte ich auch mindestens einen Fall von Schülern, die mit der aktuellen Ausgabe nichts anfangen konnten.

Eine Frage zu Mobile: Weißt du, ob das viel genutzt wird? Nutzt du das auch in deinem Unterricht?

**Comment by strenkel** [comment]
Erste Erkenntnis meinerseits ist weiterhin, den Logging-Text zu verkürzen und auf zwei (oder mehr) Übungen zu verteilen. Ggf. auch die Log-Ausgabe optisch verbessern.

Deinem Satz "Meiner Ansicht sollte console.log aber nicht zu kurz kommen, weil gerade das den Zugang zur Browser-Konsole und den anderen Developer-Tools öffnet und es da viel zu entdecken gibt." kann ich nur zustimmen. Das spricht starkt gegen jshero.log.

Deshalb folgender Vorschlag:

Man läßt jshero.log komplett fallen und wrappt console.log so, dass die log-Ausgabe zum einen wie gewöhnlich in der Browser-Konsole erscheint und dann zusätzlich wie jetzt bei jshero.log vor dem Test-Ergebnis erscheint. Dann kann man so ähnlich wie jetzt console.log einführen und muss "nur" zusätzlich erklären, dass console.log auch in die Testausgabe loggt.

Wie viele JS-Hero mobil (App und Mobile-Browser) nutzen, weiß ich nicht. Die App wird ca. 200 mal pro Monat heruntergeladen und grob 50 pro Monat lassen sie auf ihrem Handy.
Die App habe ich nicht im Unterricht genutzt. Das wäre Quatsch. Aber es könnte sinnvoll sein, wenn die Schüler/innen nebenher (in der Straßenbahn ...) mit der App üben würden.

**Comment by nelzon101** [comment]
Als Anwender ohne Lehrer und fullNewbie, wäre eine Hilfeoption in der App wünschenswert. Ich persönlich hänge am jshero.log fest. 
Hätte hier gerne die Lösung, wie man den log schreibt.

**Comment by strenkel** [comment]
@nelzon101: Eine Hilfe- und auch Lösungs-Button wurde schon des öfteren nachgefragt und diskutiert. Aktuell kann ich mich dazu nicht durchringen. Zum Selbstlernen wäre das sicher hilfreich. Für den Unterricht würde ein Hilfe-Button den Einsatz verändern. Aber hier ist noch nicht das letzte Wort gesprochen. Vielleicht kommt das. Aber zuvor möchte ich die Lektionsanzahl von 60 auf 100 erhöhen.

Die konkrete Hilfe zur jshero.log - Aufgabe würde ich lieber per Mail klären. Einfach eine Mail an
info <at> stefantrenkel.de (<at> = @, alles ohne Leerzeichen; am besten noch mit Hinweis, wo genau das Problem liegt) und ich schreibe zurück.

**Comment by strenkel** [comment]
Die Log-Übung wurden nun vereinfacht und ergänzt. Ich hoffe, dass es jetzt auch ein gutes Zusammenspiel mit dem davor Gelernten ergibt.

Die Änderungen im Detail:
- Es gibt jetzt 3 Log-Übungen. Der Übungs-Text wurde entschlackt.
- Man loggt jetzt mit console.log sowohl in die Testausgabe als auch in die Browser-Konsole.
- Der Log-Testausgabe ist ein ">" vorangestellt (wie bei MDN).

**Comment by feinstaub** [comment]
Klasse! :100:  Ich würde sagen, damit kann man den Issue schließen.

**Comment by strenkel** [comment]
Danke! Das mach ich.
