### ISSUE TITLE
11. String: toUpperCase(): Test error

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#25]
Probably a regression due to refactoring:

On http://www.jshero.net/main.html?koan=stringupper this correct solution

var toCase = function(a) {
   return a.toLowerCase() + '-' + a.toUpperCase();
}

yields a test error:

```
toCase("Ida") gibt nicht "ida-Ida", sondern "ida-IDA" zurück.
```

**Comment by strenkel** [comment]
Thanks! Fixed.
