### ISSUE TITLE
15. String: indexOf(), 2. Parameter

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#26]
My students found a loophole in the test for this koan:

http://www.jshero.net/main.html?koan=stringindexof2

```
var secondIndexOf = function(a, b) {
   return a.indexOf(b, 6);
}
```

solves the koan. One should add another test which I would place as second test:

```
secondIndexOf("aa", "a") gibt 1 zurück.
```

**Comment by strenkel** [comment]
Thank you! Fixed.
