### ISSUE TITLE
Extra-Aufgaben

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#7]
Idee für später: Möglichkeit mehrere Aufgaben pro "Blatt" (Koan) festzulegen. So kann man für ein bestimmtes Thema besser mit Wiederholungen arbeiten. Vielleicht sogar auch optionale Aufgaben, für den der Lust hat, so dass man aber trotzdem weiterkommt.

**Comment by strenkel** [comment]
Ich tendiere eher dazu, die "Blätter" möglichst kurz zu halten. Ich habe ja auch ein paar Extra-Aufgaben. Dazu habe ich einfach ein neues "Blatt" gemacht und kaum Lektions-Text reingeschrieben. Etwa #30: Drei gleiche Werte. Ich würde eher "Blätter" mit reinen Aufgaben machen und bei einer Aufgabe pro Blatt bleiben. Solche Blätter könnte man ggf. gesondert als Aufgabensammlung zusammenfassen.

**Comment by strenkel** [comment]
Optionale- oder Extra-Aufgaben sind eine gute Sache. Aber jede Aufgabe ein Blatt.
Lass ich offen als Erinnerng.

**Comment by strenkel** [comment]
Wie geschrieben, eh hier und da Praxis. Deshalb doch close.
