### ISSUE TITLE
Hinweis, wenn Javascript deaktiviert ist / Lizenz

### ISSUE THREAD

**Issue by feinstaub** [strenkel/jshero#8]
So könnte ein Hinweis für jemand aussehen, der z. B. NoScript verwendet:

"JSHero funktioniert nur, wenn du deinem Web-Browser erlaubst - zumindest für JSHero - Javascript-Code auszuführen. Gibt es gute Gründe, JSHero zu vertrauen? Ja, denn der Code steht unter einer freien Lizenz, der GPL, und muss daher unter anderem für jeden einsehbar sein: Link zum Repo"

In dem Zusammenhang könnte man überlegen:

- eine LICENSE-Datei im Root des Repositories anzulegen
- auf die AGPL zu wechseln: https://de.wikipedia.org/wiki/GNU_Affero_General_Public_License weil JSHero standardmäßig als Netzwerkdienst angeboten wird.

**Comment by strenkel** [comment]
Alle drei Sachen sind super!

**Comment by strenkel** [comment]
Auf AGPL gewechselt.

**Comment by strenkel** [comment]
Alle drei Sachen erledigt => close.
